import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const page = read('src/pages/Attendance.jsx');
const mealService = read('src/components/attendance/CustomerMealService.jsx');
const employeeQrManager = read('src/components/attendance/EmployeeMealQRManager.jsx');
const employeeQrScan = read('src/pages/EmployeeMealQRScan.jsx');
const employeeQrScanner = read('src/pages/EmployeeMealQRScanner.jsx');
const apiClient = read('src/api/base44Client.js');
const liveDiners = read('src/components/dashboard/LiveDinersPanel.jsx');
const permissions = read('src/lib/rolePermissions.js');
const foodWaste = read('src/pages/FoodWaste.jsx');
const app = read('src/App.jsx');
const server = read('server/index.js');
const pagesConfig = read('src/pages.config.js');

assert.match(page, /title="Food Consumption"/);
assert.match(page, /<CustomerMealServicePanel/);
assert.match(page, /isAdmin=\{isAdmin\}/);
assert.match(page, /canConfirm=\{canConfirm\}/);
assert.match(page, /canGenerateCoversQr=\{canGenerateCoversQr\}/);
assert.match(page, /canCreateEmployeeMealQr = isAdmin \|\| can\('create_employee_meal_qr'\)/);
assert.match(page, /<EmployeeMealQRManager canCreate=\{canCreateEmployeeMealQr\}/);
assert.match(page, /normalizeSiteType\(site\.type\) === SITE_HIERARCHY_TYPES\.PROJECT/);
assert.doesNotMatch(page, /StaffShift|AttendanceRecord|DinerScan|CustomerMealPlan/);
assert.doesNotMatch(page, /Manual Attendance|QR Attendance|Shift Schedule|Schedule Shift|Export Labor Data/);
assert.doesNotMatch(page, /<Tabs|TabsTrigger|CustomerMealServiceReport/);
assert.match(pagesConfig, /"MealService": MealService/);
assert.match(pagesConfig, /"MealQRGenerator": MealQRGenerator/);

assert.match(mealService, /Meal Service/);
assert.match(mealService, /QRCodeSVG/);
assert.match(mealService, /Covers QR/);
assert.match(mealService, /QR Scanner/);
assert.match(mealService, /buildCoversQrUrl/);
assert.match(mealService, /buildEmployeeQrScannerUrl/);
assert.match(mealService, /EmployeeMealQRScanner/);
assert.match(mealService, /service_date/);
assert.match(mealService, /site_name/);
assert.match(mealService, /menu_type/);
assert.match(mealService, /menu_category/);
assert.match(mealService, /meal_type/);
assert.match(mealService, /scopeFromUrl/);
assert.match(mealService, /Label htmlFor="meal-service-date">Date/);
assert.match(mealService, /<Label>Project<\/Label>/);
assert.match(mealService, /<Label>Menu Type<\/Label>/);
assert.match(mealService, /<Label>Menu Category<\/Label>/);
assert.match(mealService, /All Categories/);
assert.match(mealService, /categorySelectOptions/);
assert.match(mealService, /Meal Service saved for/);
assert.match(mealService, /<Label>Meal Period<\/Label>/);
assert.match(mealService, /Fully Produced Dishes/);
assert.match(mealService, /<TableHead>Dish<\/TableHead>/);
assert.match(mealService, /<TableHead>Prepared Qty<\/TableHead>/);
assert.match(mealService, /<TableHead>Portion Size<\/TableHead>/);
assert.match(mealService, /<TableHead>No\. Of Covers<\/TableHead>/);
assert.match(mealService, /availabilityQuery\.data\?\.dishes/);
assert.match(mealService, /base44\.mealService\.availability\(scope\)/);
assert.match(mealService, /base44\.mealService\.report/);
assert.match(mealService, /base44\.mealService\.confirm\(confirmationRequest\)/);
assert.match(mealService, /availabilityQuery\.data\?\.availability_snapshot/);
assert.match(mealService, /availabilitySnapshot[\s\S]*buildMealServiceConfirmationRequest/);
assert.match(mealService, /previous\.snapshot !== availabilitySnapshot[\s\S]*setIdempotencyKey\(createMealServiceIdempotencyKey\(\)\)/);
assert.match(mealService, /Prepared output changed after covers were entered/);
assert.match(mealService, /setConfirmDialogOpen\(false\)[\s\S]*setCoversByRecipe\(\{\}\)/);
assert.match(mealService, /\|\| !availabilitySnapshot/);
assert.match(mealService, /base44\.mealService\.updatePortionSize/);
assert.match(mealService, /base44\.mealService\.reverseAttendance/);
assert.match(mealService, /disabled=\{!isAdmin \|\| portionMutation\.isPending\}/);
assert.match(mealService, /disabled=\{!canConfirm \|\| availableCovers === null\}/);
assert.match(mealService, /Unconfigured —/);
assert.match(mealService, /ask an administrator to set the manual service portion/);
assert.match(mealService, /getConfirmedServicePortion\(item\)/);
assert.doesNotMatch(mealService, /item\.portion_size_grams/);
assert.match(mealService, /Save all portion-size changes before saving Meal Service/);
assert.match(mealService, /\|\| hasUnsavedPortionChanges/);
assert.match(mealService, /Save Meal Service/);
assert.match(mealService, /saves a new Meal Service request/);
assert.match(mealService, /portion size × covers/);
assert.match(mealService, /entered covers will deduct prepared production item by item/);
assert.match(mealService, /Additional requests can still be saved/);
assert.doesNotMatch(mealService, /Duplicate confirmation is blocked/);
assert.match(mealService, /Meal Service Reports &amp; History/);
assert.match(mealService, /Reverse \/ Correct Meal Service/);
assert.match(mealService, /Reason for correction/);
assert.match(mealService, /Reverse and Allow Correction/);
assert.match(mealService, /queryClient\.invalidateQueries\(\{ queryKey: \['foodWaste'\] \}\)/);
assert.doesNotMatch(mealService, /Customer Meal Plan|Arrivals Count|Customer \/ Group Name|Select completed recipes/);
assert.doesNotMatch(mealService, /prepared_meals|produced_item_batch_id|recordAttendance/);

assert.match(apiClient, /updatePortionSize\(data = \{\}\)[\s\S]*method: 'PATCH'/);
assert.match(apiClient, /confirm\(data = \{\}\)[\s\S]*\/api\/meal-service\/attendance/);
assert.match(apiClient, /emitEntityChange\('FoodWaste', \{ action: 'meal-service-leftover'/);
assert.match(apiClient, /emitEntityChange\('FoodWaste', \{ action: 'meal-service-leftover-reversal'/);
assert.match(apiClient, /staffMealQr/);
assert.match(apiClient, /\/api\/staff-meal-qr/);
assert.match(apiClient, /method: 'PATCH'/);
assert.match(apiClient, /method: 'DELETE'/);
assert.match(apiClient, /staff-meal-qr-update/);
assert.match(apiClient, /staff-meal-qr-delete/);
assert.match(apiClient, /\/api\/staff-meal-qr\/scan/);
assert.match(apiClient, /staff-meal-qr-scan/);

assert.match(employeeQrManager, /Meal QR Generator/);
assert.match(employeeQrManager, /Create QR Code/);
assert.match(employeeQrManager, /Edit Meal QR Code/);
assert.match(employeeQrManager, /Save Changes/);
assert.match(employeeQrManager, /openEditDialog/);
assert.match(employeeQrManager, /deleteQr/);
assert.match(employeeQrManager, /base44\.staffMealQr\.update/);
assert.match(employeeQrManager, /base44\.staffMealQr\.delete/);
assert.match(employeeQrManager, /Pencil/);
assert.match(employeeQrManager, /Trash2/);
assert.match(employeeQrManager, /Employee Name \*/);
assert.match(employeeQrManager, /Company ID Number \*/);
assert.match(employeeQrManager, /Active WhatsApp Mobile \*/);
assert.match(employeeQrManager, /Meal Scan Time Frames/);
assert.match(employeeQrManager, /05:00/);
assert.match(employeeQrManager, /07:00/);
assert.match(employeeQrManager, /13:00/);
assert.match(employeeQrManager, /20:00/);
assert.match(employeeQrManager, /QRCodeSVG/);
assert.match(employeeQrManager, /wa\.me/);
assert.match(employeeQrManager, /qrSvgToPngFile/);
assert.match(employeeQrManager, /new File\(\[blob\], filename, \{ type: 'image\/png' \}\)/);
assert.match(employeeQrManager, /navigator\.canShare/);
assert.match(employeeQrManager, /navigator\.share/);
assert.match(employeeQrManager, /ClipboardItem/);
assert.doesNotMatch(employeeQrManager, /url\s*\n\s*\]\.join/);
assert.match(employeeQrManager, /One scan is allowed for each meal per day/);

assert.match(employeeQrScan, /Employee Meal Scan/);
assert.match(employeeQrScan, /\/api\/staff-meal-qr\/public/);
assert.match(employeeQrScan, /Record \{meal\.label\}/);
assert.match(employeeQrScan, /Used today/);
assert.match(employeeQrScan, /Open now/);
assert.match(employeeQrScan, /Closed/);
assert.match(app, /path="\/EmployeeMealQRScan"/);
assert.match(app, /path="\/EmployeeMealQRScanner"/);

assert.match(employeeQrScanner, /Employee Meal QR Scanner/);
assert.match(employeeQrScanner, /jsQR/);
assert.match(employeeQrScanner, /parseScopeFromUrl/);
assert.match(employeeQrScanner, /Date/);
assert.match(employeeQrScanner, /Project/);
assert.match(employeeQrScanner, /Menu Type/);
assert.match(employeeQrScanner, /Menu Category/);
assert.match(employeeQrScanner, /Meal Period/);
assert.match(employeeQrScanner, /base44\.staffMealQr\.scan/);
assert.match(employeeQrScanner, /Present employee QR code/);

assert.match(server, /app\.get\('\/api\/staff-meal-qr'/);
assert.match(server, /app\.post\('\/api\/staff-meal-qr'/);
assert.match(server, /app\.patch\('\/api\/staff-meal-qr\/:id'/);
assert.match(server, /app\.delete\('\/api\/staff-meal-qr\/:id'/);
assert.match(server, /STAFF_MEAL_QR_UPDATED/);
assert.match(server, /STAFF_MEAL_QR_DELETED/);
assert.match(server, /app\.post\('\/api\/staff-meal-qr\/scan'/);
assert.match(server, /app\.get\('\/api\/staff-meal-qr\/public\/:token'/);
assert.match(server, /app\.post\('\/api\/staff-meal-qr\/public\/:token\/scan'/);
assert.match(server, /recordStaffMealQrScan/);
assert.match(server, /site_id: siteId/);
assert.match(server, /menu_type: menuType/);
assert.match(server, /menu_category: menuCategory/);
assert.match(server, /createDocument\('AttendanceRecord'/);
assert.match(server, /scan_key: scanKey/);

assert.match(liveDiners, /base44\.entities\.DinerScan/);
assert.doesNotMatch(liveDiners, /mealService\.report|MealServiceAttendance|mealServiceGroups/);

assert.match(permissions, /Food Consumption/);
assert.match(permissions, /View Meal Service production balances/);
assert.match(permissions, /Save Meal Service covers/);
assert.match(permissions, /Generate Meal Service cover QR codes/);
assert.match(permissions, /Create meal QR codes/);

assert.match(foodWaste, /analyticsWaste[\s\S]*status \|\| ''\)\.toLowerCase\(\) !== 'reversed'/);
assert.match(foodWaste, /Meal Service Leftover/);
assert.match(foodWaste, /System generated/);
assert.match(foodWaste, /Meal Service Leftover records are system managed/);
assert.match(foodWaste, /Reverse the related Meal Service request/);
assert.match(foodWaste, /System managed/);
assert.match(foodWaste, /function formatWasteQuantity[\s\S]*item\.wasted_weight_grams/);
assert.match(foodWaste, /<TableCell>\{formatWasteQuantity\(item\)\}<\/TableCell>/);
assert.match(foodWaste, /\? 'reversed' : item\.approval_status/);

console.log('PASS production-only Food Consumption UI and waste audit presentation');
