import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = (file) => fs.readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');

const database = read('server/db.js');
const schema = read('server/sql/init.sql');
const normalizedReports = read('server/normalizedOperationalReports.js');
const queue = read('server/bulkUploadQueue.js');
const client = read('src/api/base44Client.js');
const server = read('server/index.js');
const foodCostPage = read('src/pages/FoodCost.jsx');
const advancedReportsPage = read('src/pages/AdvancedReports.jsx');
const foodWastePage = read('src/pages/FoodWaste.jsx');
const productionPage = read('src/pages/Production.jsx');
const inventoryPage = read('src/pages/Inventory.jsx');
const dashboardPage = read('src/pages/Dashboard.jsx');
const reportsPage = read('src/pages/Reports.jsx');
const costControlPage = read('src/pages/CostControl.jsx');
const productivityPage = read('src/pages/ProductivityTracking.jsx');
const batchTrackingPage = read('src/pages/BatchTracking.jsx');
const compose = read('docker-compose.yml');
const deployment = read('deploy/kubernetes/foodpro.yaml');
const loadTest = read('load-tests/read-baseline.js');

assert.doesNotMatch(database, /buildEntityListQuery/);
assert.match(database, /DB_POOL_MAX/);
assert.match(database, /listDocumentsPage/);
assert.match(schema, /foodpro_entity_events/);
assert.match(schema, /idx_production_events_scope/);
assert.match(database, /FOR UPDATE SKIP LOCKED/);
assert.doesNotMatch(queue, /pendingJobs/);
assert.match(queue, /claimNextBulkUploadJob/);
assert.match(client, /fetch\('\/api\/events'/);
assert.match(client, /rangeFilters/);
assert.match(server, /rangeFilters: request\.body\?\.rangeFilters \|\| \{\}/);
assert.match(server, /filters,\s*\n\s*rangeFilters,\s*\n\s*location/s);
assert.doesNotMatch(server, /const productionCompletionQueue/);
assert.doesNotMatch(server, /const materialRequestAcknowledgementQueue/);
assert.doesNotMatch(server, /const productionProcurementActivationQueue/);
assert.doesNotMatch(server, /const menuRepeatQueue/);
assert.doesNotMatch(server, /const productionCompletionActiveIds/);
assert.doesNotMatch(server, /const materialRequestAcknowledgementActiveIds/);
assert.doesNotMatch(server, /const productionProcurementActivationActiveIds/);
assert.doesNotMatch(server, /const MENU_REPEAT_QUEUE_ACTIVE_KEYS/);
assert.doesNotMatch(server, /const menuProductionIssueActiveKeys/);
assert.match(server, /claimNextOperationalBackgroundJob/);
assert.match(server, /FOR UPDATE SKIP LOCKED/);
assert.match(server, /resumeOperationalBackgroundQueue/);
assert.match(server, /OPERATIONAL_BACKGROUND_JOB_PREPARING_STATUS = 'PREPARING'/);
assert.match(server, /buildMenuProductionIssueRecordKey/);
assert.match(server, /findExistingMenuIssueProduction/);
assert.match(server, /isProjectManagerApprovalActivation/);
assert.match(server, /app\.get\('\/api\/inventory\/production\/:id\/completion-job'/);
assert.match(server, /app\.post\('\/api\/menu-plans\/repeat-cycle'/);
assert.match(server, /app\.post\('\/api\/productions\/menu-issue'/);
assert.match(server, /response\.status\(202\)\.json/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS background_jobs/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS background_job_items/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS background_job_payload_fields/);
assert.match(schema, /idx_background_jobs_active_idempotency/);
assert.match(schema, /status IN \('PREPARING', 'QUEUED', 'PROCESSING'\)/);
assert.match(schema, /idx_background_job_payload_fields_job/);
assert.match(schema, /actor_allowed_site_ids TEXT\[\]/);
assert.match(schema, /result_entity_name TEXT/);
assert.match(server, /createOperationalBackgroundJob/);
assert.match(server, /createOperationalBackgroundJobItems/);
assert.match(server, /updateOperationalBackgroundJobItem/);
assert.match(server, /replaceOperationalBackgroundJobPayload/);
assert.match(server, /getOperationalBackgroundJobPayload/);
assert.match(server, /app\.get\('\/api\/activity\/background-jobs', requireAuth, requireRole\(\['admin'\]\)/);
assert.match(client, /listBackgroundJobs/);
assert.doesNotMatch(schema, /CREATE TABLE IF NOT EXISTS background_jobs[\s\S]*payload JSONB[\s\S]*CREATE TABLE IF NOT EXISTS background_job_items/);
assert.doesNotMatch(schema, /CREATE TABLE IF NOT EXISTS background_jobs[\s\S]*result JSONB[\s\S]*CREATE TABLE IF NOT EXISTS background_job_items/);
assert.doesNotMatch(schema, /CREATE TABLE IF NOT EXISTS background_jobs[\s\S]*actor_snapshot JSONB[\s\S]*CREATE TABLE IF NOT EXISTS background_job_items/);
assert.match(server, /OPERATIONAL_BACKGROUND_JOB_WORKERS \|\| '1'/);
assert.match(server, /FOODPRO_READ_CACHE_TTL_MS/);
assert.match(server, /CACHEABLE_ENTITY_READS/);
assert.match(server, /withReadCache/);
assert.match(server, /cacheDependenciesForEntityRead\(entity\)/);
assert.match(server, /bucket: 'stock-on-hand'/);
assert.match(server, /bucket: 'inventory-value-history'/);
assert.match(server, /app\.get\('\/api\/reports\/food-cost'/);
assert.match(server, /bucket: 'food-cost-report'/);
assert.match(server, /setPrivateCacheHeaders\(response, Math\.min\(reportCacheTtlMs, 5000\)\)/);
assert.match(server, /loadNormalizedFoodCostReport/);
assert.match(server, /app\.get\('\/api\/database\/audit'/);
assert.match(normalizedReports, /FROM meal_service_consumptions msc/);
assert.match(normalizedReports, /JOIN projects project ON project\.project_id = warehouse\.project_id/);
assert.match(normalizedReports, /report_line_layer_totals AS/);
assert.match(normalizedReports, /production_consumption_report_line_layers/);
assert.match(normalizedReports, /report_totals\.report_line_cost/);
assert.match(normalizedReports, /consumption_line_totals AS/);
assert.match(normalizedReports, /production_consumption_lines pcl/);
assert.match(normalizedReports, /NULLIF\(pml\.actual_cost, 0\)/);
assert.match(normalizedReports, /NULLIF\(pml\.estimated_cost, 0\)/);
assert.match(normalizedReports, /NULLIF\(pe\.production_cost_total, 0\)/);
assert.match(normalizedReports, /getNormalizedDatabaseAudit/);
assert.doesNotMatch(normalizedReports, /listDocuments\(/);
assert.match(client, /getFoodCost/);
assert.match(client, /getAudit/);
assert.match(compose, /OBJECT_STORAGE_ENDPOINT/);
assert.match(deployment, /kind: HorizontalPodAutoscaler/);
assert.match(deployment, /replicas: 3/);
assert.match(loadTest, /TARGET_USERS \|\| 1000/);
assert.match(loadTest, /p\(95\)<500/);
assert.match(schema, /idx_production_manifest_lines_active_output/);
assert.match(schema, /idx_food_waste_records_scope/);
assert.match(schema, /idx_meal_service_consumptions_report/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS areas/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS warehouses/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS warehouse_inventory/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS production_events/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS produced_output_batches/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS meal_service_consumptions/);
assert.match(schema, /reverses_consumption_id TEXT REFERENCES meal_service_consumptions/);
assert.match(schema, /advanced_report_schedules/);
assert.match(schema, /menu_plan_pr_runs/);
assert.match(schema, /waste_detection_logs/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS cpu_production_orders/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS cpu_dispatch_lines/);
assert.match(schema, /idx_cpu_output_batches_fifo/);
assert.match(schema, /idx_meal_service_consumptions_food_cost/);
assert.match(schema, /idx_production_events_food_cost/);
assert.match(database, /usesNormalizedCore\(entity\)/);
assert.match(database, /NORMALIZED_STORAGE_REQUIRED/);
assert.match(database, /normalizedAuxiliaryEntities/);
assert.match(database, /MaterialRequest/);
assert.match(database, /createNormalizedDocument/);
assert.match(database, /listNormalizedDocuments/);
assert.match(database, /buildNormalizedListQuery/);
assert.match(database, /COUNT\(\*\) OVER\(\) AS total_count/);
assert.match(database, /LIMIT \$\{addSqlParameter\(parameters, pageSize\)\}::integer/);
assert.match(database, /listNormalizedDocumentsPage/);
assert.doesNotMatch(database, /const allItems = await listNormalizedDocuments\(entity/);
assert.match(foodCostPage, /base44\.reports\.getFoodCost/);
assert.match(foodCostPage, /MASTER_DATA_QUERY_OPTIONS/);
assert.doesNotMatch(foodCostPage, /Production\.filter/);
assert.doesNotMatch(foodCostPage, /MealServiceConsumption\.filter/);
assert.doesNotMatch(foodCostPage, /ProducedItemBatch\.filter/);
assert.doesNotMatch(foodCostPage, /Production\.list\('-production_date', 5000\)/);
assert.doesNotMatch(foodCostPage, /MealServiceConsumption\.list\('-service_date', 5000\)/);
assert.match(advancedReportsPage, /FoodWaste\.filter/);
assert.match(advancedReportsPage, /rangeFilters: productionReportQuery\.rangeFilters/);
assert.match(advancedReportsPage, /rangeFilters: wasteReportQuery\.rangeFilters/);
assert.doesNotMatch(advancedReportsPage, /Production\.list\('-production_date', 500\)/);
assert.match(foodWastePage, /base44\.foodWaste\.list\(wasteListFilters\)/);
assert.match(foodWastePage, /productionsForWaste', productionWasteQuery/);
assert.match(foodWastePage, /invalidateCurrentWasteScope/);
assert.match(foodWastePage, /queryKey: \['foodWaste', wasteListFilters\]/);
assert.match(foodWastePage, /predicate: \(query\)/);
assert.match(foodWastePage, /'mealServiceAvailability', 'mealServiceHistory'/);
assert.match(foodWastePage, /invalidateCurrentWasteScope\(\{ inventory: true, mealService: true \}\)/);
assert.match(productionPage, /invalidateCurrentProductionScope/);
assert.match(productionPage, /foodWasteForProduction', productionLoadDate/);
assert.match(productionPage, /productionCompletionJob/);
assert.match(productionPage, /base44\.productionWorkflow\.issueMenuProduction/);
assert.match(productionPage, /isIssueSubmitPending/);
assert.match(productionPage, /refetchInterval: shouldPollCompletionJob \? 1500 : false/);
assert.match(productionPage, /completionProduction\?\.id[\s\S]*isActiveProductionCompletionJob\(completionJobForPolling\)/);
assert.match(productionPage, /Completion status/);
assert.match(productionPage, /exact: true, refetchType: 'active'/);
assert.match(productionPage, /invalidateCurrentProductionScope\(\{ inventory: true, output: true \}\)/);
assert.doesNotMatch(productionPage, /invalidateQueries\(\{ queryKey: \['productionHistoryForWasteInsights'\] \}\)/);
assert.doesNotMatch(productionPage, /invalidateQueries\(\{ queryKey: \['inventoryLots'\] \}\)/);
assert.doesNotMatch(productionPage, /Production\.list\('-production_date', 1000\)/);
assert.match(client, /getProductionCompletionJob/);
assert.match(client, /issueMenuProduction/);
assert.match(inventoryPage, /inventoryUpcomingNeeds/);
assert.doesNotMatch(inventoryPage, /Production\.list\('-production_date', 100\)/);
assert.match(dashboardPage, /productions', 'dashboard'/);
assert.match(dashboardPage, /InventoryTransaction\.filter/);
assert.doesNotMatch(dashboardPage, /Production\.list\('-production_date', 500\)/);
assert.doesNotMatch(dashboardPage, /FoodWaste\.list\('-waste_date', 500\)/);
assert.match(reportsPage, /productions', 'reports'/);
assert.match(reportsPage, /FoodWaste\.filter/);
assert.doesNotMatch(reportsPage, /Production\.list\('-production_date', 500\)/);
assert.doesNotMatch(reportsPage, /FoodWaste\.list\('-waste_date', 500\)/);
assert.match(costControlPage, /productions', 'costControl'/);
assert.match(costControlPage, /FoodWaste\.filter/);
assert.doesNotMatch(costControlPage, /Production\.list\('-production_date', 500\)/);
assert.doesNotMatch(costControlPage, /FoodWaste\.list\('-waste_date', 500\)/);
assert.match(productivityPage, /productions', 'productivityTracking'/);
assert.doesNotMatch(productivityPage, /Production\.list\('-production_date', 500\)/);
assert.match(batchTrackingPage, /productionPlansForBatchTracking', productionPlanRange/);
assert.doesNotMatch(batchTrackingPage, /Production\.list\('-production_date', 500\)/);

console.log('Scalability architecture tests passed.');
