import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = (file) => fs.readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');

const database = read('server/db.js');
const schema = read('server/sql/init.sql');
const queue = read('server/bulkUploadQueue.js');
const client = read('src/api/base44Client.js');
const server = read('server/index.js');
const foodCostPage = read('src/pages/FoodCost.jsx');
const advancedReportsPage = read('src/pages/AdvancedReports.jsx');
const foodWastePage = read('src/pages/FoodWaste.jsx');
const productionPage = read('src/pages/Production.jsx');
const inventoryPage = read('src/pages/Inventory.jsx');
const dashboardPage = read('src/pages/Dashboard.jsx');
const reportsPage = read('src/pages/Reports.jsx');
const costControlPage = read('src/pages/CostControl.jsx');
const productivityPage = read('src/pages/ProductivityTracking.jsx');
const batchTrackingPage = read('src/pages/BatchTracking.jsx');
const compose = read('docker-compose.yml');
const deployment = read('deploy/kubernetes/foodpro.yaml');
const loadTest = read('load-tests/read-baseline.js');

assert.match(database, /buildEntityListQuery/);
assert.match(database, /DB_POOL_MAX/);
assert.match(database, /listDocumentsPage/);
assert.match(schema, /foodpro_entity_events/);
assert.match(schema, /idx_entity_records_production_site_date_status_ci/);
assert.match(database, /FOR UPDATE SKIP LOCKED/);
assert.doesNotMatch(queue, /pendingJobs/);
assert.match(queue, /claimNextBulkUploadJob/);
assert.match(client, /fetch\('\/api\/events'/);
assert.match(client, /rangeFilters/);
assert.match(server, /rangeFilters: request\.body\?\.rangeFilters \|\| \{\}/);
assert.match(server, /filters,\s*\n\s*rangeFilters,\s*\n\s*location/s);
assert.match(compose, /OBJECT_STORAGE_ENDPOINT/);
assert.match(deployment, /kind: HorizontalPodAutoscaler/);
assert.match(deployment, /replicas: 3/);
assert.match(loadTest, /TARGET_USERS \|\| 1000/);
assert.match(loadTest, /p\(95\)<500/);
assert.match(schema, /idx_entity_records_production_site_date_meal_scope/);
assert.match(schema, /idx_entity_records_food_waste_report_filters/);
assert.match(schema, /idx_entity_records_meal_consumption_report_status/);
assert.match(foodCostPage, /Production\.filter/);
assert.match(foodCostPage, /MealServiceConsumption\.filter/);
assert.match(foodCostPage, /ProducedItemBatch\.filter/);
assert.match(foodCostPage, /MASTER_DATA_QUERY_OPTIONS/);
assert.doesNotMatch(foodCostPage, /Production\.list\('-production_date', 5000\)/);
assert.doesNotMatch(foodCostPage, /MealServiceConsumption\.list\('-service_date', 5000\)/);
assert.match(advancedReportsPage, /FoodWaste\.filter/);
assert.match(advancedReportsPage, /rangeFilters: productionReportQuery\.rangeFilters/);
assert.match(advancedReportsPage, /rangeFilters: wasteReportQuery\.rangeFilters/);
assert.doesNotMatch(advancedReportsPage, /Production\.list\('-production_date', 500\)/);
assert.match(foodWastePage, /base44\.foodWaste\.list\(wasteListFilters\)/);
assert.match(foodWastePage, /productionsForWaste', productionWasteQuery/);
assert.match(productionPage, /invalidateCurrentProductionScope/);
assert.match(productionPage, /foodWasteForProduction', selectedDate/);
assert.doesNotMatch(productionPage, /Production\.list\('-production_date', 1000\)/);
assert.match(inventoryPage, /inventoryUpcomingNeeds/);
assert.doesNotMatch(inventoryPage, /Production\.list\('-production_date', 100\)/);
assert.match(dashboardPage, /productions', 'dashboard'/);
assert.match(dashboardPage, /InventoryTransaction\.filter/);
assert.doesNotMatch(dashboardPage, /Production\.list\('-production_date', 500\)/);
assert.doesNotMatch(dashboardPage, /FoodWaste\.list\('-waste_date', 500\)/);
assert.match(reportsPage, /productions', 'reports'/);
assert.match(reportsPage, /FoodWaste\.filter/);
assert.doesNotMatch(reportsPage, /Production\.list\('-production_date', 500\)/);
assert.doesNotMatch(reportsPage, /FoodWaste\.list\('-waste_date', 500\)/);
assert.match(costControlPage, /productions', 'costControl'/);
assert.match(costControlPage, /FoodWaste\.filter/);
assert.doesNotMatch(costControlPage, /Production\.list\('-production_date', 500\)/);
assert.doesNotMatch(costControlPage, /FoodWaste\.list\('-waste_date', 500\)/);
assert.match(productivityPage, /productions', 'productivityTracking'/);
assert.doesNotMatch(productivityPage, /Production\.list\('-production_date', 500\)/);
assert.match(batchTrackingPage, /productionPlansForBatchTracking', productionPlanRange/);
assert.doesNotMatch(batchTrackingPage, /Production\.list\('-production_date', 500\)/);

console.log('Scalability architecture tests passed.');
